# Generated by Django 3.0 on 2019-12-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='timeline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative.Initiative'),
        ),
    ]
