# Generated by Django 3.0 on 2019-12-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_auto_20191217_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusreport',
            options={'verbose_name': 'goal', 'verbose_name_plural': 'goals'},
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', related_query_name='Post', to='initiative.Initiative'),
        ),
    ]
