# Generated by Django 3.0 on 2019-12-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_auto_20191217_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusreport',
            options={},
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', related_query_name='status_report', to='initiative.Initiative'),
        ),
    ]
