# Generated by Django 3.0 on 2019-12-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoutouts', '0003_delete_shoutoutlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoutout',
            name='likes',
        ),
    ]
