# Generated by Django 3.0 on 2019-12-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutouts', '0003_auto_20191213_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoutout',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
