# Generated by Django 3.0 on 2019-12-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutouts', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoutout',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
