# Generated by Django 3.0 on 2019-12-16 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflections', '0003_auto_20191212_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, default='Blank', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Reflection'),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Question'),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Reflection'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
