# Generated by Django 3.0 on 2019-12-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0003_auto_20191212_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
