# Generated by Django 3.0 on 2019-12-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0004_auto_20191216_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_txt', models.TextField()),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Reflection')),
            ],
        ),
    ]
