# Generated by Django 3.0.1 on 2019-12-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0004_auto_20191218_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
