# Generated by Django 3.0 on 2019-12-16 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflections', '0004_submission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Reflection'),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Question'),
        ),
        migrations.AlterField(
            model_name='questionsubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reflections.Reflection'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
