# Generated by Django 3.0 on 2019-12-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_1_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_verification',
            field=models.BooleanField(default=False),
        ),
    ]
