# Generated by Django 3.0 on 2019-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_studentoftheday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentoftheday',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentoftheday',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
