# Generated by Django 3.0 on 2019-12-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_auto_20191217_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentoftheday',
            name='date',
            field=models.DateField(),
        ),
    ]
