# Generated by Django 3.0 on 2019-12-13 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mileage_tracker', '0002_auto_20191211_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commute_amounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mileage_tracker.DriveToWork')),
                ('distance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mileage_tracker.DistanceToWork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
