# Generated by Django 3.0 on 2019-12-16 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mileage_tracker', '0004_auto_20191213_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetowork',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
